include_guard( DIRECTORY )

list(APPEND BASIS_SOURCES
  ${BASIS_DIR}/application/app_runners.h
  ${BASIS_DIR}/application/app_runners.cc
  #
  ${BASIS_DIR}/application/application.hpp
  ${BASIS_DIR}/application/application.cc
  #
  ${BASIS_DIR}/application/application_configuration.hpp
  ${BASIS_DIR}/application/application_state.hpp
  ${BASIS_DIR}/application/export.hpp
  ${BASIS_DIR}/application/platform_detection.hpp
  #
  ${BASIS_DIR}/application/paths/path_provider.hpp
  ${BASIS_DIR}/application/paths/application_paths.hpp
  ${BASIS_DIR}/application/paths/application_get_path.hpp
  ${BASIS_DIR}/application/paths/path_id.hpp
  ${BASIS_DIR}/application/paths/path_provider.cc
  #
  ${BASIS_DIR}/application/posix/paths/application_get_path.cc
  ${BASIS_DIR}/application/posix/application_configuration_posix.hpp
  #
  ${BASIS_DIR}/test/do_nothing_promise.h
  ${BASIS_DIR}/test/do_nothing_promise.cc
  #
  ${BASIS_DIR}/promise/abstract_promise.cc
  ${BASIS_DIR}/promise/abstract_promise.h
  ${BASIS_DIR}/promise/all_container_executor.h
  ${BASIS_DIR}/promise/all_tuple_executor.h
  ${BASIS_DIR}/promise/dependent_list.cc
  ${BASIS_DIR}/promise/dependent_list.h
  ${BASIS_DIR}/promise/finally_executor.cc
  ${BASIS_DIR}/promise/finally_executor.h
  ${BASIS_DIR}/promise/helpers.cc
  ${BASIS_DIR}/promise/helpers.h
  ${BASIS_DIR}/promise/no_op_promise_executor.cc
  ${BASIS_DIR}/promise/post_task_executor.h
  ${BASIS_DIR}/promise/promise.h
  ${BASIS_DIR}/promise/promise.h
  ${BASIS_DIR}/promise/race_container_executor.h
  ${BASIS_DIR}/promise/race_tuple_executor.h
  ${BASIS_DIR}/promise/promise_executor.cc
  ${BASIS_DIR}/promise/promise_executor.h
  ${BASIS_DIR}/promise/promise_result.h
  ${BASIS_DIR}/promise/promise_value.cc
  ${BASIS_DIR}/promise/promise_value.h
  ${BASIS_DIR}/promise/post_promise.cc
  ${BASIS_DIR}/promise/post_promise.h
  ${BASIS_DIR}/promise/then_and_catch_executor.cc
  ${BASIS_DIR}/promise/then_and_catch_executor.h
  #
  ${BASIS_DIR}/core/numeric_static_cast.hpp
  ${BASIS_DIR}/core/pimpl.hpp
  ${BASIS_DIR}/immutable.hpp
  ${BASIS_DIR}/weak_handle.hpp
  ${BASIS_DIR}/enum_set.hpp
  ${BASIS_DIR}/polymorphic_downcast.hpp
  ${BASIS_DIR}/ltrace.hpp
  ${BASIS_DIR}/periodic_prioritized_task_heap.hpp
  ${BASIS_DIR}/periodic_prioritized_task_heap.cc
  ${BASIS_DIR}/time_step/FixedTimeStep.hpp
  ${BASIS_DIR}/time_step/FixedTimeStep.cpp
  ${BASIS_DIR}/time_step/FixedTimeStepLoop.hpp
  ${BASIS_DIR}/time_step/FixedTimeStepLoop.cpp
  ${BASIS_DIR}/timer/IntervalTimer.hpp
  ${BASIS_DIR}/timer/IntervalTimer.cpp
  ${BASIS_DIR}/concurrency/LockFreeProducerConsumerQueue.hpp
  ${BASIS_DIR}/concurrency/LockFreeProducerConsumerQueue.cpp
  ${BASIS_DIR}/log/Logger.cpp
  ${BASIS_DIR}/log/Logger.hpp
  ${BASIS_DIR}/task_run/task_run_util.cc
  ${BASIS_DIR}/task_run/task_run_util.hpp
)
