include_guard( DIRECTORY )

list(APPEND BASIS_SOURCES
  ${BASIS_DIR}/application/app_runners.h
  ${BASIS_DIR}/application/app_runners.cc
  #
  ${BASIS_DIR}/base_environment.h
  ${BASIS_DIR}/base_environment.cc
  #
  ${BASIS_DIR}/path_provider.h
  ${BASIS_DIR}/path_provider.cc
  #
  ${BASIS_DIR}/plugin_manager.h
  ${BASIS_DIR}/plugin_manager.cc
  #
  ${BASIS_DIR}/doctest_util.h
  ${BASIS_DIR}/doctest_util.cc
  #
  ${BASIS_DIR}/i18n/i18n.h
  ${BASIS_DIR}/i18n/i18n.cc
  ${BASIS_DIR}/i18n/icu_util.h
  ${BASIS_DIR}/i18n/icu_util.cc
  #
  ${BASIS_DIR}/memory/any_ptr.h
  #
  ${BASIS_DIR}/threading/thread_pool_util.h
  ${BASIS_DIR}/threading/thread_pool_util.cc
  ${BASIS_DIR}/threading/thread_health_checker.h
  ${BASIS_DIR}/threading/thread_health_checker.cc
  #
  ${BASIS_DIR}/annotations/asio_guard_annotations.h
  ${BASIS_DIR}/annotations/asio_guard_annotations.cc
  #
  ${BASIS_DIR}/promise/post_promise.h
  ${BASIS_DIR}/promise/post_promise.cc
  #
  ${BASIS_DIR}/task/prioritized_once_task_heap.h
  ${BASIS_DIR}/task/prioritized_once_task_heap.cc
  ${BASIS_DIR}/task/periodic_task_executor.h
  ${BASIS_DIR}/task/periodic_task_executor.cc
  ${BASIS_DIR}/task/task_util.cc
  ${BASIS_DIR}/task/task_util.h
  ${BASIS_DIR}/task/periodic_check.cc
  ${BASIS_DIR}/task/periodic_check.h
  ${BASIS_DIR}/task/periodic_validate_until.cc
  ${BASIS_DIR}/task/periodic_validate_until.h
  ${BASIS_DIR}/task/alarm_manager.h
  ${BASIS_DIR}/task/alarm_manager.cc
  #
  ${BASIS_DIR}/application/application.h
  ${BASIS_DIR}/application/application.cc
  ${BASIS_DIR}/application/application_configuration.h
  ${BASIS_DIR}/application/application_state.h
  ${BASIS_DIR}/application/export.h
  ${BASIS_DIR}/application/paths/path_provider.h
  ${BASIS_DIR}/application/paths/application_paths.h
  ${BASIS_DIR}/application/paths/application_get_path.h
  ${BASIS_DIR}/application/paths/path_id.h
  ${BASIS_DIR}/application/paths/path_provider.cc
  ${BASIS_DIR}/application/posix/paths/application_get_path.cc
  ${BASIS_DIR}/application/posix/application_configuration_posix.h
  #
  ${BASIS_DIR}/time_step/fixed_time_step.h
  ${BASIS_DIR}/time_step/fixed_time_step.cc
  ${BASIS_DIR}/time_step/fixed_time_step_loop.h
  ${BASIS_DIR}/time_step/fixed_time_step_loop.cc
  #
  ${BASIS_DIR}/checked_optional.h
  #
  ${BASIS_DIR}/ECS/components/relationship/parent_entity.h
  #
  ${BASIS_DIR}/ECS/components/relationship/first_child_in_linked_list.h
  #
  ${BASIS_DIR}/ECS/components/relationship/top_level_children_count.h
  #
  ${BASIS_DIR}/ECS/components/relationship/child_siblings.h
  #
  ${BASIS_DIR}/ECS/helpers/relationship/remove_child_from_top_level.h
  #
  ${BASIS_DIR}/ECS/helpers/relationship/foreach_top_level_child.h
  #
  ${BASIS_DIR}/ECS/helpers/relationship/view_top_level_children.h
  #
  ${BASIS_DIR}/ECS/helpers/relationship/prepend_child_entity.h
  #
  ${BASIS_DIR}/ECS/helpers/lifetime/populate_delayed_construction_components.h
  ${BASIS_DIR}/ECS/helpers/lifetime/populate_delayed_construction_components.cc
  #
  ${BASIS_DIR}/ECS/unsafe_context.cc
  ${BASIS_DIR}/ECS/unsafe_context.h
  #
  ${BASIS_DIR}/ECS/sequence_local_context.cc
  ${BASIS_DIR}/ECS/sequence_local_context.h
  #
  ${BASIS_DIR}/ECS/safe_registry.cc
  ${BASIS_DIR}/ECS/safe_registry.h
  #
  ${BASIS_DIR}/ECS/ecs.h
  ${BASIS_DIR}/ECS/ecs.cc
  #
  ${BASIS_DIR}/ECS/tags.h
  ${BASIS_DIR}/ECS/tags.cc
)
